---
- name: Install and start apache
  hosts: all
  become: true

  tasks:
    - name: Ensure the httpd package is installed
      ansible.builtin.package:
        name: httpd
        state: present

    - name: Create the index.html file
      ansible.builtin.template:
        src: files/index.html
        dest: /var/www/html/

    - name: Start the httpd service if needed
      ansible.builtin.service:
        name: httpd
        state: started

    - name: Open firewall port 80.
      ansible.builtin.firewalld:
        port: 80/tcp
        permanent: true
        state: enabled
        immediate: true
        zone: public