---
- name: Make API calls to AAP.
  hosts: localhost
  tasks:
    - name: Check that you can connect (GET) to a page and it returns a status 200
      ansible.builtin.uri:
        url: http://team-one-controller-team-one.apps.openshift.lan/#/login
        validate_certs: false

    - name: Check that you can connect (GET) to a page and it returns a status 200
      ansible.builtin.uri:
        url: http://team-one-controller-team-one.apps.openshift.lan/#/login
        validate_certs: false

    - name: Check that you can connect (GET) to a page and it returns a status 200
      ansible.builtin.uri:
        url: http://team-one-controller-team-one.apps.openshift.lan/#/login
        validate_certs: false

    - name: Check that you can connect (GET) to a page and it returns a status 200
      ansible.builtin.uri:
        url: http://team-one-controller-team-one.apps.openshift.lan/#/login
        validate_certs: false

    - name: Check that you can connect (GET) to a page and it returns a status 200
      ansible.builtin.uri:
        url: http://team-one-controller-team-one.apps.openshift.lan/#/login
        validate_certs: false
          
    - name: Check that you can connect (GET) to a page and it returns a status 200
      ansible.builtin.uri:
        url: http://team-one-controller-team-one.apps.openshift.lan/#/login
        validate_certs: false
          
    - name: Check that you can connect (GET) to a page and it returns a status 200
      ansible.builtin.uri:
        url: http://team-one-controller-team-one.apps.openshift.lan/#/login
        validate_certs: false
          
    - name: Check that you can connect (GET) to a page and it returns a status 200
      ansible.builtin.uri:
        url: http://team-one-controller-team-one.apps.openshift.lan/#/login
        validate_certs: false

    - name: Check that you can connect (GET) to a page and it returns a status 200
      ansible.builtin.uri:
        url: http://team-one-controller-team-one.apps.openshift.lan/#/login
        validate_certs: false

    - name: Check that you can connect (GET) to a page and it returns a status 200
      ansible.builtin.uri:
        url: http://team-one-controller-team-one.apps.openshift.lan/#/login
        validate_certs: false

    - name: Check that you can connect (GET) to a page and it returns a status 200
      ansible.builtin.uri:
        url: http://team-one-controller-team-one.apps.openshift.lan/#/login
        validate_certs: false

    - name: Check that you can connect (GET) to a page and it returns a status 200
      ansible.builtin.uri:
        url: http://team-one-controller-team-one.apps.openshift.lan/#/login
        validate_certs: false

    - name: Check that you can connect (GET) to a page and it returns a status 200
      ansible.builtin.uri:
        url: http://team-one-controller-team-one.apps.openshift.lan/#/login
        validate_certs: false
          
    - name: Check that you can connect (GET) to a page and it returns a status 200
      ansible.builtin.uri:
        url: http://team-one-controller-team-one.apps.openshift.lan/#/login
        validate_certs: false
          
    - name: Check that you can connect (GET) to a page and it returns a status 200
      ansible.builtin.uri:
        url: http://team-one-controller-team-one.apps.openshift.lan/#/login
        validate_certs: false
          
    - name: Check that you can connect (GET) to a page and it returns a status 200
      ansible.builtin.uri:
        url: http://team-one-controller-team-one.apps.openshift.lan/#/login
        validate_certs: false
