---
- name: Patch hosts with Ansible.
  hosts: all
  become: true
  tasks:
    - name: Update all packages on RHEL hosts.
      ansible.builtin.package:
        name: "*"
        state: present
      when: ansible_facts['os_family'] == "RedHat"
