---
- name: Test playbook to install packages.
  hosts: all
  become: true
  tasks:
    - name: Install firewalld packages
      ansible.builtin.package:
        name: firewalld
        state: present

    - name: enable firewalld service and make it immediate.
      ansible.builtin.systemd:
        name: firewalld
        enabled: true
        state: started

    - name: allow ports 9090, 9100 and 9200 with firewalld.
      ansible.posix.firewalld:
        port: "{{ item }}"
        permanent: true
        state: enabled
        immediate: true
      loop:
        - 9090/tcp
        - 9100/tcp
        - 9200/tcp

    - name: reload firewalld.
      ansible.builtin.systemd:
        name: firewalld
        state: reloaded
