---
- name: Configure the AAP cluster.
  hosts: localhost
  gather_facts: no
  vars:
    validate_certs: false
  tasks:
    - name: Set the license using a file
      ansible.controller.license:
        manifest: "files/manifest_automation-controller_example.zip"
        controller_config_file: files/controller_auth

    - name: Create a SCM/Git credentials to sync project.
      ansible.controller.credential:
        name: SCM Credential
        organization: Default
        state: present
        credential_type: Source Control
        inputs:
          username: username
          ssh_key_data: "{{ lookup('file', 'files/id_rsa') }}"
        controller_config_file: files/controller_auth

    - name: Create Machine credentials for job_template execution. 
      ansible.controller.credential:
        name: username-creds
        organization: Default
        state: present
        credential_type: Machine
        inputs:
          username: username
          password: 'password'
          ssh_key_data: "{{ lookup('file', 'files/id_rsa') }}"
        controller_config_file: files/controller_auth

    - name: Configure SCM project from git to populate playbooks for job templates. 
      ansible.controller.project:
        name: "Hammer - Demo"
        organization: "Default"
        scm_url: <github_url>
        scm_type: git
        credential: SCM Credential
        update_project: true
        controller_config_file: files/controller_auth

    - name: Add Home Lab inventory to group hosts in later for job execution. 
      ansible.controller.inventory:
        name: "Home Lab"
        organization: Default
        state: present
        controller_config_file: files/controller_auth

    - name: Create and add hosts into Home Lab inventory. 
      ansible.controller.host:
        name: "{{ item }}"
        inventory: "Home Lab"
        enabled: true
        controller_config_file: files/controller_auth 
      loop:
        - aap.lan
        - pah.lan
        - db.lan
        - bastion.lan

    - name: Add the customee Execution Environment to Controller.
      ansible.controller.execution_environment:
        name: "Custom EE"
        image: <private_automation_hub_url/customee:latest>
        state: present
        pull: missing
        controller_config_file: files/controller_auth 

    - name: Create the ping hosts job template to run against the aap cluster. 
      ansible.controller.job_template:
        name: "Ping Hosts"
        job_type: run
        organization: "Default"
        inventory: "Home Lab"
        project: "Hammer - Demo"
        playbook: "ping.yml"
        forks: 5
        become_enabled: true
        credentials: 
          - "username-creds"
        controller_config_file: files/controller_auth

    - name: Launch a job with inventory and credential
      ansible.controller.job_launch:
        job_template: "Ping Hosts"
        controller_config_file: files/controller_auth
        wait: true
