---
- name: download and install AAP from the bastion
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags: aap_installation

  vars_files:
    - inventory_vars/variables.yml

  #Comment out any roles not being used, for example if you're not downloading the setup bundle directly from RH, then remove the aap_setup_download role. 
  roles:
    - infra.aap_utilities.aap_setup_download
    - infra.aap_utilities.aap_setup_prepare
    - infra.aap_utilities.aap_setup_install
