---
- name: Configure the AAP cluster.
  hosts: localhost
  gather_facts: no
  tasks:
    - name:  Remove SCM credential.
      ansible.controller.credential:
        name: SCM Credential
        organization: Default
        state: absent
        credential_type: Source Control
        controller_config_file: files/controller_auth
        inputs:
          username: hammer-redhat
          ssh_key_data: "{{ lookup('file', 'files/id_rsa') }}"

    - name: Add user as a system administrator
      ansible.controller.user:
        username: chrhamme
        password: redhat123
        email: chrhamme@hammer.org
        superuser: yes
        state: absent
        controller_config_file: files/controller_auth

    - name: Remove Machine credential. 
      ansible.controller.credential:
        name: chrhamme-ssh
        controller_config_file: files/controller_auth
        organization: Default
        state: absent
        credential_type: Machine
        inputs:
          username: chrhamme
          password: '12!@qwQWasASzxZX'
          ssh_key_data: "{{ lookup('file', 'files/id_rsa') }}"

    - name: Add the customee Execution Environment to Controller.
      ansible.controller.execution_environment:
        name: "Custom EE"
        image: pah.lan/hammer/customee
        validate_certs: false
        state: absent
        controller_config_file: files/controller_auth

    - name: Remove SCM project.
      ansible.controller.project:
        name: "Hammer - Demo"
        organization: "Default"
        scm_update_on_launch: true
        scm_url: git@github.com:hammer-redhat/demos.git
        scm_type: git
        credential: SCM Credential
        state: absent
        update_project: true
        controller_config_file: files/controller_auth

    - name: Remove Home Lab inventory. 
      ansible.controller.inventory:
        name: "Home Lab"
        organization: Default
        state: absent
        controller_config_file: files/controller_auth

    - name: Remove the ping job template.
      ansible.controller.job_template:
        name: "Ping Hosts"
        job_type: run
        organization: "Default"
        inventory: "Home Lab"
        project: "Hammer - Demo"
        playbook: "ping.yml"
        credentials: 
          - "chrhamme-ssh"
        state: absent
        controller_config_file: files/controller_auth
