---
- name: Get your facts straight
  hosts: nodes
  become: yes

  tasks:

  - name: FIRST TASK | Display facts
    debug:
      var: ansible_facts
    tags: first_task

  - name: SECOND TASK | display a specific fact
    lineinfile:
      path: /etc/hosts
      line: "{{ default_ipv4.address }}" "{{ ansible_facts.fqdn }}" "{{ ansible_facts.hostname }}"
      state: present
    tags: second_task

  - name: THIRD TASK | display lvm fact.
    debug:
      var: ansible_lvm
    tags: third_task

  - name: FOURTH TASK | Get Service Facts
    service_facts:
    tags: fourth_task

  - name: FIFTH TASK | print service facts
    debug:
      var: ansible_facts.services['httpd.service']
    tags: fifth_task