---
- name: Get your facts straight
  hosts: all
  become: yes

  tasks:
  - name: Get Service Facts
    service_facts: 

  - name: display ipv4 address.
    debug:
      msg: IP "{{ansible_default_ipv4.address}}" DNS "{{ ansible_dns }}"

#  - name: print service facts
#    debug:
#      var: ansible_facts.services['httpd.service']