---
- name: Get your facts straight
  hosts: all
  become: yes

  tasks:

  - name: FIRST TASK | Display facts
    debug:
      var: ansible_facts
    tags: first_task

  - name: SECOND TASK | using a fact as a variable
    lineinfile:
      path: /home/chrhamme/hostname_test
      regex: "^this is my hostname:"
      line: "this is my hostname: {{ ansible_hostname }}"
      state: present
      create: yes
    tags: second_task

  - name: THIRD TASK | display a specific fact.
    debug:
      var: ansible_lvm
    tags: third_task

  - name: FOURTH TASK | Get Service Facts
    service_facts:
    tags: fourth_task

#  - name: FIFTH TASK | print service facts
#    debug:
#      var: ansible_facts.services['httpd.service']
#    tags: fifth_task