---
- name: Get failed services
  hosts: all
  become: yes

  tasks:

  - name: Get Service Facts
    service_facts:

  - name: display ipv4 address.
    debug:
      var: 
        - ansible_default_ipv4.address
        - ansible_dns

#  - name: print service facts
#    debug:
#      var: ansible_facts.services
