---
- name: Deploy and start Apache HTTPD service
  hosts: nodes 
  become: true
 
  tasks:
    - name: Required packages are installed and up to date
      yum:
        name: httpd
        state: present
      when: ansible_distribution == "RedHat"

    - name: Get service facts. 
      service_facts: 
        var: ansible_facts.services['httpd.service']['state']