---
- name: Deploy and start Apache HTTPD service
  hosts: nodes 
  become: true
 
  tasks:
    - name: Required packages are installed and up to date
      yum:
        name: httpd
        state: latest 
      when: 
        - ansible_distribution == "RedHat"
        - ansible_distribution_major_version == "7"
      register: httpd_state

    - name: Start the httpd service
      service:
        name: httpd
        state: started
        enabled: yes
      when: httpd_state.changed

    - name: Gather service facts
      service_facts:

    - name: Get httpd facts.
      debug: 
        var: ansible_facts.services['httpd.service']