---
- name: Get your facts straight
  hosts: all
  become: true
  tasks:
    - name: FIRST TASK | Display facts
      ansible.builtin.debug:
        var: ansible_facts
      tags: first_task

    - name: SECOND TASK | Using a fact as a variable
      ansible.builtin.debug:
        msg: "this is my hostname: {{ ansible_hostname }}"
      tags: second_task

    - name: THIRD TASK | Display a specific fact.
      ansible.builtin.debug:
        var: ansible_lvm
      tags: third_task

    - name: FOURTH TASK | Get Service Facts
      ansible.builtin.service_facts:
      tags: fourth_task
