---
# tasks file for user.
- name: Create user accounts
  user:
    name: "{{ item.username }}"
    groups: "{{ item.groups }}"
    comment: "{{ item.username }}"
    state: "{{ item.user_state }}"
  loop: "{{ users }}"

- name: Add authorized keys
  authorized_key:
    user: "{{ item.username }}"
    key: "{{ lookup('file', 'files/'+ item.username + '.key.pub') }}"
  loop: "{{ users }}"

- name: Change password expiration.
  shell: chage -M  99999 "{{ item.username }}"
  loop: "{{ users }}"

- name: Ensure PermitRootLogin in /etc/ssh/sshd_config is set to no. 
  lineinfile:
    path: /etc/ssh/sshd_config
    regex: '^#PermitRootLogin'
    line: PermitRootLogin yes
    state: present
  notify: sshd

- name: Ensure PermitRootLogin in /etc/ssh/sshd_config is set to no. 
  lineinfile:
    path: /etc/ssh/sshd_config
    regex: '^#PubkeyAuthentication'
    line: PubkeyAuthentication yes
    state: present
  notify: sshd
