---
- name: Create user accounts
  user:
    name: "{{ item.username }}"
    groups: "{{ item.groups }}"
    comment: "{{ item.username }}"
    state: "{{ item.user_state }}"
  loop: "{{ users }}"

- name: Add authorized keys
  authorized_key:
    user: "{{ item.username }}"
    key: "{{ lookup('file', 'files/'+ item.username + '.key.pub') }}"
  loop: "{{ users }}"

- name: Change password to expire in 99999 days. 
  shell: chage -M  99999 "{{ item.username }}"
  loop: "{{ users }}"