---
# tasks file for user.
- name: Create user accounts
  user:
    name: "{{ item.username }}"
    groups: "{{ item.groups }}"
    comment: "{{ item.username }}"
    state: "{{ item.user_state }}"
    generate_ssh_key: yes
  loop: "{{ users }}"

- name: Change password expiration.
  shell: chage -M  99999 "{{ item.username }}"
  loop: "{{ users }}"

- name: Ensure PermitRootLogin in /etc/ssh/sshd_config is set to no. 
  lineinfile:
    path: /etc/ssh/sshd_config
    regex: '^#PermitRootLogin'
    line: PermitRootLogin no
    state: present
  notify: sshd