---
# tasks file for users
- name: Create users
  user:
    name: "{{ users.username }}"
    group: "{{ users.groups }}"
    state: "{{ users.user_state }}"
    password: "{{ users.password }}"
    update_password: always
  loop: 
    - users

- name: Disable Root login via SSH.
  lineinfile:
    path: /etc/ssh/sshd_config
    regex: '^#PermitRootLogin'
    line: PermitRootLogin no
    create: yes
  notify: sshd