---
# tasks file for users
- name: Create users
  user:
    name: "{{ users.name }}"
    group: "{{ users.membership }}"
    shell: "{{ users.shells }}"
    state: "{{ users.status }}"
    update_password: "{{ users.pass }}"

- name: Disable Root login via SSH.
  lineinfile:
    path: /etc/ssh/sshd_config
    regex: '^#PermitRootLogin'
    line: PermitRootLogin no
    create: yes
  notify: sshd