---
# tasks file for user.
- name: Create user accounts
  user:
    name: "{{ item.username }}"
    groups: "{{ item.groups }}"
    comment: "{{ item.username }}"
    state: "{{ item.user_state }}"
  loop: "{{ users }}"

- name: Change password to expire in 99999 days. 
  shell: chage -M  99999 "{{ item.username }}"
  loop: "{{ users }}"

- name: Add AllowUsers lineinfile in /etc/ssh/sshd_config
  lineinfile:
    path: /etc/ssh/sshd_config
    regex: '^#PermitRootLogin'
    line: PermitRootLogin no
    state: present
  notify: sshd