---
- name: Testing variables
  hosts: nodes
  become: true
  gather_facts: false
  vars_files:
    - variables.yml
  tasks:
    - name: FIRST TASK | install package | Variable included in task
      yum:
        name: "{{ install_package }}"
        state: latest
      tags: first_task
      vars:
        - install_package: firewalld

    - name: SECOND TASK | Variables in vars_files | Maintain desired state for packages
      yum:
        name: "{{ item.package_name }}"
        state: "{{ item.desired_state }}"
      loop: "{{ packages }}"
      tags: second_task

    - name: THIRD TASK | Variables in inventory file | SELinux module
      selinux:
        policy: "{{ selinux_policy }}"
        state: "{{ selinux_state }}"
      tags: third_task
