---

- name: edit /etc/hosts
  lineinfile:
    dest: /etc/hosts
    line: "{{ sat6_ip }} {{ sat6_fqdn }} hammer-satellite"

- name: Store the ca consumer cert on the host.
  shell: curl --insecure --output katello-ca-consumer-latest.noarch.rpm https://hammer-satellite.attlocal.net/pub/katello-ca-consumer-latest.noarch.rpm

- name: Install the local ca consumer cert.
  shell: yum localinstall -y katello-ca-consumer-latest.noarch.rpm

- name: run a sub-man clean to remove any old subscription data.
  shell: subscription-manager clean

- name: Register the host using the RHEL 8 activation key. 
  shell: subscription-manager register --org="hammer-lab" --activationkey="host-registration-rhel-8"
  when: "ansible_distribution_version == '8.3'"
    
- name: Register the host using the RHEL 7 activation key. 
  shell: subscription-manager register --org="hammer-lab" --activationkey="host-registration"
  when: "ansible_distribution_version == '7.9'"

- name: install required packages
  yum:
    name: "{{ item }}"
    state: present
  loop: "{{ packages }}"

- name: ensure root .ssh directory exists.
  file: 
    path: /root/.ssh
    state: directory
    owner: root
    group: root
    mode: 0700

- name: Configure host for remote execution from Satellite.
  shell: curl https://hammer-satellite.attlocal.net:9090/ssh/pubkey >> /root/.ssh/authorized_keys