---
- name: Testing variables
  hosts: nodes 
  become: yes
  gather_facts: no
  vars_files:
    - variables.yml

  tasks:

    - name: FIRST TASK | Ping hosts | Variable included in task
      connection: "{{ connection_type }}"
      yum: 
        name: "{{ install_package }}"
        state: latest
      vars: 
        - install_package: firewalld
      tags: first_task

    - name: SECOND TASK | Variables in vars_files | Maintain desired state for packages
      yum:
        name: "{{ item.package_name }}"
        state: "{{ item.desired_state }}"
      loop: "{{ packages }}"
      tags: second_task

    - name: THIRD TASK | Variables in inventory file | SELinux module
      selinux:
        policy: "{{ selinux_policy }}"
        state: "{{ selinux_state }}"
      tags: third_task
