---
- name: Test vars
  hosts: nodes 
  become: yes
  vars_files:
    - variables.yml

  tasks:
    - name: Install required packages.
      yum:
        name: "{{ item.package_name }}"
        state: "{{ item.desired_state }}"
      loop: "{{ packages }}"

    - name: SELinux module
      selinux:
        policy: "{{ selinux_policy }}"
        state: "{{ selinux_state }}"
