---
- name: Test vars
  hosts: all 
  become: yes
  vars_files:
    - variables.yml

  tasks:
    - name: Install required packages.
      yum:
        name: "{{ item.package_name }}"
        state: "{{ item.desired_state }}"
      loop:
        - "{{ packages }}"