---
- name: Testing variables
  hosts: nodes 
  become: yes
  vars_files:
    - variables.yml

  tasks:

    - name: FIRST TASK | Ping hosts | Variable included in task
      connection: "{{ connection_type }}"
      ping:
      vars: 
        - connection_type: ssh

    - name: SECOND TASK | Variables in vars_files | Maintain desired state for packages
      yum:
        name: "{{ item.package_name }}"
        state: "{{ item.desired_state }}"
      loop: "{{ packages }}"

    - name: THIRD TASK | Variables in inventory file | SELinux module
      selinux:
        policy: "{{ selinux_policy }}"
        state: "{{ selinux_state }}"
