---
- name: Test vars
  hosts: nodes 
  become: yes
  vars_files:
    - variables.yml

  tasks:

    - name: Ping hosts
      connection: "{{ connection_type }}"
      ping:
      vars: 
        - connection_type: ssh

    - name: Maintain desired state for packages.
      yum:
        name: "{{ item.package_name }}"
        state: "{{ item.desired_state }}"
      loop: "{{ packages }}"

    - name: SELinux module
      selinux:
        policy: "{{ selinux_policy }}"
        state: "{{ selinux_state }}"
