---
- name: Test vars
  hosts: all 
  become: yes
  vars_files:
    - test.yml
    - test2.yml

  tasks:
    - name: yum install
      yum:
        name: "{{ packages }}"
        state: present

    - name: yum install
      yum:
        name: "{{ package }}"
        state: present
