---
- name: Listen for URL events
  hosts: nfs.lan
  gather_facts: false

  sources:
    - name: Match events from webserver
      ansible.eda.url_check:
        urls:
          - http://nfs.lan/index.html
        delay: 10

  rules:
    - name: Webserver is up
      condition: event.url_check.status == "up"
      action:
        debug:
          msg: The website is up and running

    - name: Webserver is down
      condition: event.url_check.status == "down"
      action:
        run_job_template:
          name: website_down_index.yml

    - name: Webserver is down (service stopped)
      condition: >
        event.url_check.status == "down"
        and event.url_check.error_msg is search("Cannot connect to host")
      action:
        run_job_template:
          name: website_down_service.yml