---
- name: Restoring apache service
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Display a message
      ansible.builtin.debug:
        msg: "Website is down!"

    - name: Start apache service
      ansible.builtin.service:
        name: httpd
        state: started